# fly.toml app configuration file generated for crop-recommendation-api on 2025-04-26T08:48:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crop-recommendation-api'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
